# Autoware transform params
# TODO: Resolve code duplication, this information is already in the base_link -> velodyne TF

tf_x: 1.35
tf_y: 0
tf_z: 1.59
tf_roll: 0.0
tf_pitch: 0.0523599
tf_yaw: 0.0
localizer: velodyne
