# Autoware transform params
# TODO: Resolve code duplication, this information is already in the base_link -> velodyne TF

tf_x: 1.19
tf_y: 0
tf_z: 2.03
tf_roll: 0.0
tf_pitch: 0.0
tf_yaw: 0.0
localizer: velodyne
